
package transducer;

/**
 * Events that the transducer can fire
 */
public enum TEvent
{
	// global events
	START,
	STOP,
	SET_RECIPE,

	// conveyor
	CONVEYOR_DO_START,
	CONVEYOR_DO_STOP,

	// sensor
	SENSOR_GUI_PRESSED,
	SENSOR_GUI_RELEASED,

	// popup
	POPUP_DO_MOVE_UP,
	POPUP_GUI_MOVED_UP,
	POPUP_DO_MOVE_DOWN,
	POPUP_GUI_MOVED_DOWN,
	POPUP_RELEASE_GLASS,
	POPUP_GUI_LOAD_FINISHED,
	POPUP_GUI_RELEASE_FINISHED, 

	// truck
	TRUCK_DO_LOAD_GLASS,
	TRUCK_GUI_LOAD_FINISHED,
	TRUCK_DO_EMPTY,
	TRUCK_GUI_EMPTY_FINISHED,
	TRUCK_DO_LEAVE,
	TRUCK_GUI_LEAVE_FINISHED,
	TRUCK_DO_RETURN,
	TRUCK_GUI_RETURN_FINISHED,

	// workstations
	WORKSTATION_DO_ACTION,
	WORKSTATION_RELEASE_GLASS,
	WORKSTATION_GUI_ACTION_FINISHED,
	WORKSTATION_DO_LOAD_GLASS,
	WORKSTATION_LOAD_FINISHED,
	WORKSTATION_RELEASE_FINISHED,
	WORKSTATION_DO_CHANGE_ANIMATION_TIME,
	WORKSTATION_DO_REMOVE_GLASS, 
	WORKSTATION_MACHINE_BREAK,
	
	//bin and "Glass Ghosts"
	BIN_CREATE_PART,
	BIN_PART_CREATED, 
	
}
